lib/elixir_todo_workshop_web/router.ex
defmodule ElixirTodoWorkshopWeb.Router do
  use ElixirTodoWorkshopWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElixirTodoWorkshopWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/lists", ListController
    resources "/items", ItemController, only: [:edit, :update, :delete]
    get "/items/:list", ItemController, :index
    get "/items/new/:list", ItemController, :new
    post "/items/:list", ItemController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirTodoWorkshopWeb do
  #   pipe_through :api
  # end
end

lib/elixir_todo_workshop/todo/item.ex
defmodule ElixirTodoWorkshop.Todo.Item do
  use Ecto.Schema
  import Ecto.Changeset


  schema "items" do
    field :description, :string
    belongs_to :list, ElixirTodoWorkshop.Todo.List, on_replace: :nilify

    timestamps()
  end

  @doc false
  def changeset(item, attrs) do
    item
    |> cast(attrs, [:description])
    |> validate_required([:description])
  end

  def changeset_create(item, attrs, list) do
    item
    |> cast(attrs, [:description])
    |> validate_required([:description])
    |> put_assoc(:list, list)
  end
end

lib/elixir_todo_workshop_web/controllers/item_controller.ex
defmodule ElixirTodoWorkshopWeb.ItemController do
  use ElixirTodoWorkshopWeb, :controller

  alias ElixirTodoWorkshop.Todo
  alias ElixirTodoWorkshop.Todo.Item

  def index(conn, %{"list" => list} = _params) do
    list = Todo.get_list!(list)
    render(conn, "index.html", list: list, items: list.items)
  end

  def new(conn, %{"list" => list} = _params) do
    list = Todo.get_list!(list)
    changeset = Todo.change_item(%Item{})
    render(conn, "new.html", list: list, changeset: changeset)
  end

  def create(conn, %{"list" => list, "item" => item_params}) do
    list = Todo.get_list!(list)
    case Todo.create_item(item_params, list) do
      {:ok, item} ->
        conn
        |> put_flash(:info, "Item created successfully.")
        |> redirect(to: item_path(conn, :index, item.list))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    item = Todo.get_item!(id)
    render(conn, "show.html", item: item)
  end

  def edit(conn, %{"id" => id}) do
    item = Todo.get_item!(id)
    changeset = Todo.change_item(item)
    render(conn, "edit.html", item: item, changeset: changeset)
  end

  def update(conn, %{"id" => id, "item" => item_params}) do
    item = Todo.get_item!(id)

    case Todo.update_item(item, item_params) do
      {:ok, item} ->
        conn
        |> put_flash(:info, "Item updated successfully.")
        |> redirect(to: item_path(conn, :index, item.list))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", item: item, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    item = Todo.get_item!(id)
    {:ok, _item} = Todo.delete_item(item)

    conn
    |> put_flash(:info, "Item deleted successfully.")
    |> redirect(to: item_path(conn, :index, item.list))
  end
end

lib/elixir_todo_workshop_web/views/item_view.ex
defmodule ElixirTodoWorkshopWeb.ItemView do
  use ElixirTodoWorkshopWeb, :view
end

lib/elixir_todo_workshop_web/templates/item/edit.html.eex
<h2>Edit Item</h2>

<%= render "form.html", Map.put(assigns, :action, item_path(@conn, :update, @item)) %>

<span><%= link "Back", to: item_path(@conn, :index, @item.list) %></span>

lib/elixir_todo_workshop_web/templates/item/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= text_input f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/elixir_todo_workshop_web/templates/item/index.html.eex
<h2><%= @list.name %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for item <- @items do %>
    <tr>
      <td><%= item.description %></td>

      <td class="text-right">
        <span><%= link "Edit", to: item_path(@conn, :edit, item), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: item_path(@conn, :delete, item), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Item", to: item_path(@conn, :new, @list) %></span>
<span><%= link "Back", to: list_path(@conn, :index) %></span>

lib/elixir_todo_workshop_web/templates/item/new.html.eex
<h2>New Item</h2>

<%= render "form.html", Map.put(assigns, :action, item_path(@conn, :create, @list)) %>

<span><%= link "Back", to: item_path(@conn, :index, @list) %></span>

lib/elixir_todo_workshop_web/templates/item/show.html.eex
<h2>Show Item</h2>

<ul>

  <li>
    <strong>Description:</strong>
    <%= @item.description %>
  </li>

</ul>

<span><%= link "Edit", to: item_path(@conn, :edit, @item) %></span>
<span><%= link "Back", to: item_path(@conn, :index, @item.list) %></span>