lib/elixir_todo_workshop_web/router.ex
defmodule ElixirTodoWorkshopWeb.Router do
  use ElixirTodoWorkshopWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElixirTodoWorkshopWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/lists", ListController
    resources "/items", ItemController, only: [:edit, :update, :delete]
    get "/items/:list", ItemController, :index
    get "/items/new/:list", ItemController, :new
    post "/items/:list", ItemController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirTodoWorkshopWeb do
  #   pipe_through :api
  # end
end

lib/elixir_todo_workshop/todo/list.ex
defmodule ElixirTodoWorkshop.Todo.List do
  use Ecto.Schema
  import Ecto.Changeset


  schema "lists" do
    field :name, :string
    has_many :items, ElixirTodoWorkshop.Todo.Item

    timestamps()
  end

  @doc false
  def changeset(list, attrs) do
    list
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/elixir_todo_workshop_web/controllers/list_controller.ex
defmodule ElixirTodoWorkshopWeb.ListController do
  use ElixirTodoWorkshopWeb, :controller

  alias ElixirTodoWorkshop.Todo
  alias ElixirTodoWorkshop.Todo.List

  def index(conn, _params) do
    lists = Todo.list_lists()
    render(conn, "index.html", lists: lists)
  end

  def new(conn, _params) do
    changeset = Todo.change_list(%List{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"list" => list_params}) do
    case Todo.create_list(list_params) do
      {:ok, _list} ->
        conn
        |> put_flash(:info, "List created successfully.")
        |> redirect(to: list_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    list = Todo.get_list!(id)
    render(conn, "show.html", list: list)
  end

  def edit(conn, %{"id" => id}) do
    list = Todo.get_list!(id)
    changeset = Todo.change_list(list)
    render(conn, "edit.html", list: list, changeset: changeset)
  end

  def update(conn, %{"id" => id, "list" => list_params}) do
    list = Todo.get_list!(id)

    case Todo.update_list(list, list_params) do
      {:ok, _list} ->
        conn
        |> put_flash(:info, "List updated successfully.")
        |> redirect(to: list_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", list: list, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    list = Todo.get_list!(id)
    {:ok, _list} = Todo.delete_list(list)

    conn
    |> put_flash(:info, "List deleted successfully.")
    |> redirect(to: list_path(conn, :index))
  end
end

lib/elixir_todo_workshop_web/views/list_view.ex
defmodule ElixirTodoWorkshopWeb.ListView do
  use ElixirTodoWorkshopWeb, :view
end

lib/elixir_todo_workshop_web/templates/list/edit.html.eex
<h2>Edit List</h2>

<%= render "form.html", Map.put(assigns, :action, list_path(@conn, :update, @list)) %>

<span><%= link "Back", to: list_path(@conn, :index) %></span>

lib/elixir_todo_workshop_web/templates/list/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/elixir_todo_workshop_web/templates/list/index.html.eex
<h2>TODO Lists</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for list <- @lists do %>
    <tr>
      <td><%= link(list.name, to: item_path(@conn, :index, list)) %></td>

      <td class="text-right">
        <span><%= link "Show", to: item_path(@conn, :index, list), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: list_path(@conn, :edit, list), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: list_path(@conn, :delete, list), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New List", to: list_path(@conn, :new) %></span>

lib/elixir_todo_workshop_web/templates/list/new.html.eex
<h2>New List</h2>

<%= render "form.html", Map.put(assigns, :action, list_path(@conn, :create)) %>

<span><%= link "Back", to: list_path(@conn, :index) %></span>

lib/elixir_todo_workshop_web/templates/list/show.html.eex
<h2>Show List</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @list.name %>
  </li>

</ul>

<span><%= link "Edit", to: list_path(@conn, :edit, @list) %></span>
<span><%= link "Back", to: list_path(@conn, :index) %></span>